language: python
python:
    - "3.5"

install: "pip install -r requirements.txt"

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3  # Give xvfb time to start
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

#script: nosetests tests/test_pykeyboardevent.py -sv
script: "python xtest.py"

branches:
    only:
        - ci
        - ci-develop
